### ISSUE TITLE
Any Working Example this with codefresh 

### ISSUE THREAD

**Issue by moses-gangipogu** [codefresh-io/steps#105]
hi,

i am new to codefresh , and trying sub modules.
```
steps:
    get_git_token:
        title: Reading Github token
        stage: prepare
        image: codefresh/cli
        commands:
           - cf_export GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -y .spec.data.auth.password)
    main_clone:
        title: Cloning repository...
        stage: prepare
        type: git-clone
        arguments:
            repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
            git: eds_bitbucket
            revision: '${{CF_BRANCH}}'
    init_submodules:
        title: Init Submodules
        stage: prepare
        image: codefreshio/git-image:latest
        working_directory: ${{main_clone}} 
        environment:
              - CF_SUBMODULE_SYNC=true
              - CF_SUBMODULE_UPDATE_RECURSIVE=true
```

I tried this but does nothing
