### ISSUE TITLE
add aws eks update-kubeconfig

### ISSUE THREAD

**Issue by 45cali** [codefresh-io/steps#383]
Currently the helm step only takes advantage of kube context that has already been configured.
Can you add an option for this step to run this prior to running helm upgrade?
```
aws eks --region <region> update-kubeconfig --name <cluster name> --alias <friendly name>
```

**Comment by 45cali** [comment]
or can you at least add aws-cli so in our kubeconfig this runs
```
- name: arn:aws:eks:<region>:<account>:cluster/<cluster>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/<vesion>
      args:
      - --region
      - <region>
      - eks
      - get-token
      - --cluster-name
      - <cluster>
      command: aws
      env:
      - name: AWS_PROFILE
        value: <profile>
        ```
