### ISSUE TITLE
TIMEOUT_MINS default doesn't seem to work for codefresh-run

### ISSUE THREAD

**Issue by ToddBradley** [codefresh-io/steps#462]
I see in the code where `TIMEOUT_MINS` has a default value of 45 (minutes). But I'm not convinced that actually works. I have a couple pipelines that run about 2 hours but don't time out.

The pipeline definition is very simple:

```
version: "1.0"

steps:
  test:
    title: "Running All Mid Tier Tests on develop-shadow"
    type: codefresh-run
    arguments:
      PIPELINE_ID: platform/SystemTestAndReport
      VARIABLE: 
        - SUT_NAMESPACE=develop-shadow
        - PYTEST_MARK=all
```
